name: fxendit
description: The easy way to use Xendit Software Development Kit (SDK) in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/fxendit
repository: https://github.com/salkuadrat/fxendit

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=3.13.4"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xendit.fxendit
        pluginClass: FxenditPlugin
